# Generated by Django 5.0.6 on 2024-06-06 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_homework'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='oy',
        ),
    ]
