# Generated by Django 5.0.6 on 2024-06-06 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_homework_oy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Homework',
        ),
    ]
