# Generated by Django 5.0.4 on 2024-06-08 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_homework'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Homework',
        ),
    ]
